import { CollectionTemplate, FieldDefinition } from './types';

export const FIELD_TYPES: { type: string; label: string }[] = [
  { type: 'text', label: 'Short Text' },
  { type: 'long_text', label: 'Long Text' },
  { type: 'number', label: 'Number' },
  { type: 'date', label: 'Date' },
  { type: 'rating', label: 'Rating (1-5)' },
  { type: 'boolean', label: 'Checkbox' },
  { type: 'select', label: 'Dropdown' },
];

export const TEMPLATES: CollectionTemplate[] = [
  {
    id: 'general',
    name: 'General',
    icon: '✨',
    description: 'Archive miscellaneous items like tickets, stamps, and more.',
    accentColor: 'stone',
    fields: [
      { id: 'brand', label: 'Brand/Maker', type: 'text' },
      { id: 'category', label: 'Category', type: 'text' },
      { id: 'date', label: 'Date Acquired', type: 'date' },
      { id: 'location', label: 'Location', type: 'text' },
    ],
    displayFields: ['brand', 'date'],
    badgeFields: ['category'],
  },
  {
    id: 'chocolate',
    name: 'Chocolate Collection',
    icon: '🍫',
    description: 'Track origin, cocoa percentage, and tasting notes.',
    accentColor: 'orange',
    fields: [
      { id: 'brand', label: 'Brand', type: 'text' },
      { id: 'cocoa_percent', label: 'Cocoa %', type: 'number' },
      { id: 'origin', label: 'Origin', type: 'text' },
      { id: 'flavor_notes', label: 'Flavor Notes', type: 'text' },
      { id: 'type', label: 'Type', type: 'select', options: ['Dark', 'Milk', 'White', 'Inclusion', 'Raw'] },
    ],
    displayFields: ['brand', 'cocoa_percent'],
    badgeFields: ['type', 'origin'],
  },
  {
    id: 'vinyl',
    name: 'Vinyls',
    icon: '🎵',
    description: 'Organize your record collection by artist, label, and year.',
    accentColor: 'indigo',
    fields: [
      { id: 'artist', label: 'Artist', type: 'text' },
      { id: 'label', label: 'Label', type: 'text' },
      { id: 'year', label: 'Year', type: 'number' },
      { id: 'genre', label: 'Genre', type: 'text' },
      { id: 'condition', label: 'Condition', type: 'select', options: ['Mint (M)', 'Near Mint (NM)', 'Very Good Plus (VG+)', 'Very Good (VG)', 'Good (G)'] },
    ],
    displayFields: ['artist', 'year'],
    badgeFields: ['genre', 'condition'],
  },
  {
    id: 'perfume',
    name: 'Perfumes',
    icon: '✨',
    description: 'Manage your fragrances, notes, and perfume houses.',
    accentColor: 'rose',
    fields: [
      { id: 'house', label: 'House', type: 'text' },
      { id: 'concentration', label: 'Concentration', type: 'select', options: ['Extrait', 'Parfum', 'EDP', 'EDT', 'Cologne'] },
      { id: 'main_accords', label: 'Main Accords', type: 'text' },
      { id: 'nose', label: 'Nose', type: 'text' },
    ],
    displayFields: ['house', 'concentration'],
    badgeFields: ['main_accords'],
  },
  {
    id: 'sneakers',
    name: 'Sneakers',
    icon: '👟',
    description: 'Keep track of your sneaker collection and colorways.',
    accentColor: 'emerald',
    fields: [
      { id: 'brand', label: 'Brand', type: 'text' },
      { id: 'model', label: 'Model', type: 'text' },
      { id: 'colorway', label: 'Colorway', type: 'text' },
      { id: 'size', label: 'Size', type: 'number' },
      { id: 'style_code', label: 'Style Code', type: 'text' },
    ],
    displayFields: ['model', 'size'],
    badgeFields: ['brand'],
  },
];