import { CollectionTemplate, FieldDefinition } from "./types";

export const FIELD_TYPES: { type: string; label: string }[] = [
  { type: "text", label: "Short Text" },
  { type: "long_text", label: "Long Text" },
  { type: "number", label: "Number" },
  { type: "date", label: "Date" },
  { type: "rating", label: "Rating (1-5)" },
  { type: "boolean", label: "Checkbox" },
  { type: "select", label: "Dropdown" },
];

export const TEMPLATES: CollectionTemplate[] = [
  {
    id: "general",
    name: "General Archive",
    icon: "✨",
    description:
      "Archive miscellaneous items like tickets, stamps, and curious finds.",
    accentColor: "stone",
    fields: [
      { id: "brand", label: "Brand/Maker", type: "text" },
      { id: "category", label: "Category", type: "text" },
      { id: "date", label: "Date Acquired", type: "date" },
      { id: "location", label: "Location", type: "text" },
    ],
    displayFields: ["brand", "date"],
    badgeFields: ["category"],
  },
  {
    id: "chocolate",
    name: "Chocolate Vault",
    icon: "🍫",
    description:
      "Track terroir, cocoa percentages, and nuanced flavor profiles.",
    accentColor: "orange",
    fields: [
      { id: "brand", label: "Chocolatier", type: "text" },
      { id: "cocoa_percent", label: "Cocoa %", type: "number" },
      { id: "origin", label: "Origin / Estate", type: "text" },
      { id: "flavor_notes", label: "Tasting Notes", type: "text" },
      {
        id: "type",
        label: "Type",
        type: "select",
        options: ["Dark", "Milk", "White", "Inclusion", "Ruby", "Raw"],
      },
      { id: "batch", label: "Batch No.", type: "text" },
    ],
    displayFields: ["brand", "cocoa_percent"],
    badgeFields: ["type", "origin"],
  },
  {
    id: "vinyl",
    name: "Vinyl Archives",
    icon: "🎵",
    description:
      "Organize your analog sound library by artist, pressings, and quality.",
    accentColor: "indigo",
    fields: [
      { id: "artist", label: "Artist", type: "text" },
      { id: "label", label: "Label", type: "text" },
      { id: "year", label: "Release Year", type: "number" },
      { id: "genre", label: "Genre", type: "text" },
      {
        id: "speed",
        label: "Speed",
        type: "select",
        options: ["33 1/3 RPM", "45 RPM", "78 RPM"],
      },
      {
        id: "condition",
        label: "Condition",
        type: "select",
        options: [
          "Mint (M)",
          "Near Mint (NM)",
          "Very Good Plus (VG+)",
          "Very Good (VG)",
          "Good (G)",
          "Fair (F)",
        ],
      },
    ],
    displayFields: ["artist", "year"],
    badgeFields: ["genre", "condition"],
  },
  {
    id: "perfume",
    name: "Scent Library",
    icon: "✨",
    description:
      "Manage your fragrances, olfactive notes, and perfumery houses.",
    accentColor: "rose",
    fields: [
      { id: "house", label: "Fragrance House", type: "text" },
      { id: "nose", label: "Perfumer (Nose)", type: "text" },
      {
        id: "concentration",
        label: "Concentration",
        type: "select",
        options: [
          "Extrait de Parfum",
          "Parfum",
          "Eau de Parfum",
          "Eau de Toilette",
          "Eau de Cologne",
          "Body Mist",
        ],
      },
      { id: "notes_top", label: "Top Notes", type: "text" },
      { id: "notes_heart", label: "Heart Notes", type: "text" },
      { id: "notes_base", label: "Base Notes", type: "text" },
      {
        id: "season",
        label: "Best Season",
        type: "select",
        options: ["Spring", "Summer", "Autumn", "Winter", "All Year"],
      },
    ],
    displayFields: ["house", "concentration"],
    badgeFields: ["season"],
  },
  {
    id: "sneakers",
    name: "Sneaker Gallery",
    icon: "👟",
    description: "Curate your footwear rotation and limited colorways.",
    accentColor: "emerald",
    fields: [
      { id: "brand", label: "Brand", type: "text" },
      { id: "model", label: "Model", type: "text" },
      { id: "colorway", label: "Colorway", type: "text" },
      { id: "size", label: "Size (US)", type: "number" },
      { id: "style_code", label: "Style Code", type: "text" },
      { id: "deadstock", label: "Deadstock", type: "boolean" },
    ],
    displayFields: ["model", "size"],
    badgeFields: ["brand", "colorway"],
  },
  {
    id: "spirits",
    name: "Spirit Collection",
    icon: "🥃",
    description: "Document rare bottles, vintages, and distillation details.",
    accentColor: "amber",
    fields: [
      { id: "brand", label: "Distillery", type: "text" },
      {
        id: "type",
        label: "Spirit Type",
        type: "select",
        options: [
          "Whisky",
          "Gin",
          "Rum",
          "Tequila",
          "Mezcal",
          "Cognac",
          "Vodka",
        ],
      },
      { id: "age", label: "Age Statement", type: "text" },
      { id: "abv", label: "ABV %", type: "number" },
      { id: "region", label: "Region", type: "text" },
    ],
    displayFields: ["brand", "age"],
    badgeFields: ["type", "region"],
  },
];
